import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "background-stitch": "#0f131b",
        "error-stitch": "#ffb4ab",
        "error-container": "#93000a",
        "inverse-on-surface": "#2c3039",
        "inverse-primary": "#005ac2",
        "inverse-surface": "#dfe2ee",
        "on-background": "#dfe2ee",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "on-primary": "#002e6a",
        "on-primary-container": "#00285d",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",
        "on-secondary": "#182f59",
        "on-secondary-container": "#9fb5e7",
        "on-secondary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#304671",
        "on-surface": "#dfe2ee",
        "on-surface-variant": "#c2c6d6",
        "on-tertiary": "#502400",
        "on-tertiary-container": "#461f00",
        "on-tertiary-fixed": "#311400",
        "on-tertiary-fixed-variant": "#723600",
        "outline-stitch": "#8c909f",
        "outline-variant": "#424754",
        "primary-stitch": "#adc6ff",
        "primary-container": "#4d8eff",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "secondary-stitch": "#b1c6f9",
        "secondary-container": "#304671",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#b1c6f9",
        "surface-stitch": "#0f131b",
        "surface-bright": "#353942",
        "surface-container": "#1c2028",
        "surface-container-high": "#262a33",
        "surface-container-highest": "#31353e",
        "surface-container-low": "#181c24",
        "surface-container-lowest": "#0a0e16",
        "surface-dim": "#0f131b",
        "surface-tint": "#adc6ff",
        "surface-variant": "#31353e",
        "tertiary": "#ffb786",
        "tertiary-container": "#df7412",
        "tertiary-fixed": "#ffdcc6",
        "tertiary-fixed-dim": "#ffb786"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ["General Sans", "Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
